#En este notebook aplicaremos las diferentes etapas del pre procesamiento:

In [1]:
import numpy as np
import pandas as pd
%matplotlib inline

Definición del problem

Contexto
Según la Organización Mundial de la Salud (OMS), el accidente cerebrovascular es la 2ª causa de muerte a nivel mundial, responsable de aproximadamente el 11% del total de muertes. Este conjunto de datos se utiliza para predecir si es probable que un paciente sume un accidente cerebrovascular en función de los parámetros de entrada como el sexo, la edad, varias enfermedades y el estado de tabaquismo. Cada fila de los datos proporciona información relavante sobre el paciente.

Información de atributos

1) id: identificador único\
2) género: "Masculino", "Femenino" u "Otro"\
3) edad: edad del paciente\
4) hipertensión: 0 si el paciente no tiene hipertensión, 1 si el paciente tiene hipertensión\
5) heart_disease: 0 si el paciente no tiene ninguna enfermedad cardíaca, 1 si el paciente tiene una enfermedad cardíaca\
6) ever_married: "No" o "Sí"\
7) work_type: "hijos", "Govt_jov", "Never_worked", "privado" o "trabajador por cuenta propia"\
8) Residence_type: "Rural" o "Urbano"\
9) avg_glucose_level: nivel promedio de glucosa en sangre\
10) BMI: índice de masa corporal\
11) smoking_status: "anteriormente fumado", "nunca fumado", "fuma" o "Desconocido"*\
12) accidente cerebrovascular: 1 si el paciente tuvo un accidente cerebrovascular o 0 si no

In [5]:
# Reemplaza el nombre por el de tu archivo real
df = pd.read_csv("healthcare-dataset-stroke-data.csv")

Información del DataSet preliminar.

In [6]:
df.head(100)

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1
...,...,...,...,...,...,...,...,...,...,...,...,...
95,2458,Female,78.0,0,0,Yes,Private,Rural,235.63,32.3,never smoked,1
96,35512,Female,70.0,0,0,Yes,Self-employed,Rural,76.34,24.4,formerly smoked,1
97,56841,Male,58.0,0,1,Yes,Private,Rural,240.59,31.4,smokes,1
98,8154,Male,57.0,1,0,Yes,Govt_job,Urban,78.92,27.7,formerly smoked,1
99,4639,Female,69.0,0,0,Yes,Govt_job,Urban,82.81,28.0,never smoked,1

In [ ]:
df.shape

(5110, 12)

El DataSet contine 12 atributos o variables (columnas) y 5110 registros (filas).

In [ ]:
df.sample(100)

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
671,967,Male,61.0,0,1,Yes,Private,Urban,88.27,NaN,never smoked,0
3131,45175,Male,18.0,0,0,No,Private,Urban,80.07,22.3,Unknown,0
484,53910,Female,48.0,0,0,Yes,Self-employed,Rural,132.08,31.6,smokes,0
3231,6295,Female,57.0,0,0,Yes,Govt_job,Urban,104.36,19.2,smokes,0
3460,40509,Female,23.0,0,0,No,Private,Urban,91.19,28.3,never smoked,0
...,...,...,...,...,...,...,...,...,...,...,...,...
3217,3379,Female,61.0,0,0,Yes,Private,Urban,87.52,23.7,Unknown,0
512,27757,Male,31.0,0,0,Yes,Private,Urban,88.78,35.8,smokes,0
4323,17174,Male,15.0,0,0,No,children,Rural,78.90,23.0,Unknown,0
4242,24585,Male,40.0,0,0,Yes,Govt_job,Urban,115.07,36.9,never smoked,0
4784,70497,Female,81.0,1,1,Yes,Private,Rural,126.34,27.4,smokes,0

Revisar la contidad de valores nulos del DataFrame, el atributo bmi tiene valores nulos o missing values.

In [ ]:
df.isnull().sum()

id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  201
smoking_status         0
stroke                 0
dtype: int64